name: Go test actions

on: [push, pull_request]

jobs:

  test-and-build:
    strategy:
      matrix: 
        go-version: ['1.20','1.21']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build ./cmd/main.go

    - name: Test
      run: go test -v ./...
